name: Compile using @zeit/ncc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tool3/ncc@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          src: 'src/securityscorecard-generator.js'
